import { ThemeProvider } from "./Components/ThemeToggler.jsx";
import UserContext from "./Context/UserContext.jsx";

import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
        cz-shortcut-listen="true"
        suppressHydrationWarning={true}
      >
        <ThemeProvider>
          <UserContext>
            {" "}
            {/* <ThemeToggler /> */}
            {children}
          </UserContext>
        </ThemeProvider>
      </body>
    </html>
  );
}
